name: AGL SK Repo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0 # ou outra versão que você esteja utilizando
    - name: Install Jekyll and Bundler
      run: gem install jekyll bundler
    - name: Build the site with Jekyll
      run: |
        cd website/aglsk/pages
        bundle install
        bundle exec jekyll build
    - name: Upload _site directory
      uses: actions/upload-artifact@v3
      with:
        name: site
        path: website/aglsk/pages/_site
